//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.15

pub mod prelude;

pub mod alliance;
pub mod capsuleer;
pub mod corporation;
pub mod member;
pub mod outpost;
pub mod problem;
pub mod skill;
